releasefix/SUPP-853 Non Prod banner display
HDRUK/gateway-web pull request #1027
Opened 2022-02-09 11:58 UTC by kandaj

Fix to display non production banner for all environments  expect production

2022-02-09 12:01 UTC, cdjreekie approved these changes

2022-02-09 12:06 UTC, cdjreekie approved these changes
lgtm

2022-02-09 12:44 UTC, ThinkingMonkeyLtd requested changes

2022-02-09 12:44 UTC, ThinkingMonkeyLtd commented on src/pages/commonComponents/searchBar/SearchBar.js
> +		const showUatBanner = process.env.REACT_APP_SHOW_NON_PROD_BANNER ? !!JSON.parse(process.env.REACT_APP_SHOW_NON_PROD_BANNER) : false;
Isn't this the same as const showUatBanner = process.env.REACT_APP_SHOW_NON_PROD_BANNER?

2022-02-09 13:48 UTC, ThinkingMonkeyLtd approved these changes

2022-02-10 08:57 UTC, dannitahdruk approved these changes
lgtm!

2022-02-10 12:59 UTC, ThinkingMonkeyLtd commented on src/pages/commonComponents/searchBar/SearchBar.js
> +		const showUatBanner = urlEnv !== 'prod' ? true : false;
const showUatBanner = urlEnv !== 'prod' ? true : false; can just be const showUatBanner = urlEnv !== 'prod';

2022-11-25 10:49 UTC, closed without merging