Story/datause widget
HDRUK/gateway-web pull request #1252
Opened 2022-08-23 10:08 UTC by kandaj

2022-08-23 15:27 UTC, ThinkingMonkeyLtd requested changes

2022-08-23 15:27 UTC, ThinkingMonkeyLtd commented on public/locales/en-GB/translation.json
> -            "howToDesc": "Below is an interactive example of how your widget could look and be used. Please note that this design is compatible with mobile devices and can be resized to fit anywhere
Conditions(s)?

2022-08-23 15:27 UTC, ThinkingMonkeyLtd commented on src/components/Cta/Cta.stories.mdx
> +<<<<<<< HEAD
Conmflicts

2022-08-23 15:27 UTC, ThinkingMonkeyLtd commented on src/components/Cta/__snapshots__/Cta.test.js.snap
> +<<<<<<< HEAD
Conflicts

2022-08-23 15:27 UTC, ThinkingMonkeyLtd commented on src/pages/commonComponents/AdvancedSearchModal/AdvancedSearchModal.js
> +import React, { useState } from 'react';
Don't think this exists in dev / release anymore

2022-08-23 15:27 UTC, ThinkingMonkeyLtd commented on src/pages/dashboard/Components/ActivityLogCard/__snapshots__/ActivityLogCard.test.jsx.snap
> +<<<<<<< HEAD
Conflicts

2022-08-24 11:24 UTC, kymmeh approved these changes

2022-08-24 11:28 UTC, kymmeh approved these changes

2022-08-26 08:34 UTC, ThinkingMonkeyLtd approved these changes

2022-08-26 08:38 UTC, ThinkingMonkeyLtd approved these changes

2022-08-26 08:59 UTC, merged