Story/gat 1377
HDRUK/gateway-web pull request #1270
Opened 2022-08-31 10:58 UTC by GK230

2022-09-01 11:18 UTC, kymmeh commented
@GK230 is this branch working for you? I'm seeing multiple errors. I've put a PR in to resolve some of them: https://github.com/HDRUK/gateway-web/pull/1273. It's probably best to wait for Peter to review this too as there are conflicts with changes he made.

2022-09-01 11:22 UTC, kymmeh commented
Any empty file has been added: `src/pages/search/temp`

2022-09-01 11:22 UTC, kymmeh commented
Geeta have you had the design review with Marlon? I think there are some visual tweaks too.

2022-09-02 07:46 UTC, ThinkingMonkeyLtd requested changes

2022-09-02 07:46 UTC, ThinkingMonkeyLtd commented on src/pages/commonComponents/savedPreferencesModalOld/SavedPreferencesModalOld.js
> +import axios from 'axios';
Is this used anywhere now it has been renamed as old or is it a backup? If it's a backup please get rid of it, these things tend to have a way of being stale and hanging around. If we need it back we can get it from git commits. The same applies to styles.

2022-09-02 07:46 UTC, ThinkingMonkeyLtd commented on src/pages/search/SearchPage.js
> +                                            Save
This exists in translations

2022-09-02 07:57 UTC, ThinkingMonkeyLtd commented
Echoing Kymme's comments, branch does not work. Search does not render - if this is a result of doing a merge in github itself when updating an out of date branch, make sure you pull it down to check it works.

2022-09-02 07:58 UTC, ThinkingMonkeyLtd requested changes

2022-09-02 07:58 UTC, ThinkingMonkeyLtd commented on src/pages/search/SearchPage.js
> +import ToolsSearchSort from './components/ToolsSearchResults/ToolsSearchSort'import searchService from '../../services/search/search';
* ERROR HERE *

2022-09-07 11:49 UTC, kymmeh submitted a review, later dismissed

2022-09-07 14:14 UTC, dannitahdruk submitted a review, later dismissed

2022-09-07 15:35 UTC, kymmeh approved these changes

2022-09-07 15:42 UTC, ThinkingMonkeyLtd approved these changes

2022-09-07 15:53 UTC, merged