fixed broken link
HDRUK/gateway-web pull request #1425
Opened 2022-11-14 15:39 UTC by GK230

2022-11-14 15:44 UTC, dannitahdruk reviewed
better this need to be a parameter in the environment file and not hardcoded.

2022-11-14 15:47 UTC, kymmeh commented
@GK230 please could you add the ticket number to the PR title?

2022-11-14 16:52 UTC, kymmeh requested changes

2022-11-14 16:52 UTC, kymmeh commented on .env
> +NEWSLETTER_EXAMPLE=https://hdruk-ac-uk-1.hubspotpagebuilder.com/hdr-innovation-gateway-november-update
Could you add URL to the name? ie `NEWSLETTER_EXAMPLE_URL`

2022-11-14 16:52 UTC, kymmeh commented on src/pages/registration/CompleteRegistration.js
> +                                href={process.env.NEWSLETTER_EXAMPLE}>
Once I've raised a PR I tend to click the "Files changed" tab and have a scan down (it's not bullet proof), but sometimes means you pick up things like this ^^ (don't think we want the privacy policy pointing to the newsletter)

2022-11-15 08:54 UTC, dannitahdruk reviewed
- all hardcoded values who are in your path need to be moved in env file;
- since this repository is public, this env file must not be in Github (public), but there must be a dedicated page in Confluence for this.

2022-11-15 09:14 UTC, kymmeh commented
> * all hardcoded values who are in your path need to be moved in env file;
> * since this repository is public, this env file must not be in Github (public), but there must be a dedicated page in Confluence for this.

@dannitahdruk we're aware of this and there's a task to remove .env from the repo. At the moment there is nothing sensitive within there.

2022-11-15 09:15 UTC, kymmeh commented
@GK230 Please document any .env variables in the README.md (you'll see there's a section at the bottom)

2022-11-15 10:31 UTC, kymmeh approved these changes

2022-11-15 10:39 UTC, loki-sinclair-hdruk approved these changes

2022-11-15 10:40 UTC, merged