Fixed typo in login modal
HDRUK/gateway-web pull request #1452
Opened 2022-12-02 13:30 UTC by GK230

"identity"

2022-12-02 13:47 UTC, dannitahdruk approved these changes

2022-12-02 14:01 UTC, kymmeh commented
@GK230 there's a unit test failing. The snapshot needs updating.

2022-12-02 14:01 UTC, kymmeh requested changes
@GK230 there's a unit test failing. The snapshot needs updating.

2022-12-05 11:12 UTC, kymmeh approved these changes

2022-12-05 11:16 UTC, merged