Adding workflowName to assignNotify request body
HDRUK/gateway-web pull request #334
Opened 2020-11-17 15:46 UTC by RichardHobbsPA

2020-11-18 10:17 UTC, PaulMcCaffertyPA approved these changes

2020-11-18 17:16 UTC, CMarksPA approved these changes

2020-11-20 12:40 UTC, CMarksPA requested changes
Request a change and removal of workflowName

2020-11-20 12:40 UTC, CMarksPA commented on src/pages/DataAccessRequest/components/AssignWorkflowModal/AssignWorkflowModal.js
> +                    "workflowName": workflow.workflowName
Richard, the backend for the PUT here has the workflowId being passed, the API finds the workflow by ID which will return the workflow name for you to use. I feel this should be removed.

2020-11-20 14:12 UTC, closed without merging