New button to send DAR info by email
HDRUK/gateway-web pull request #470
Opened 2021-02-11 10:15 UTC by massimocianfroccaPA

Added a button in the DAR page to send an email with the DAR info.
The button is enabled only if the DAR is in progress.

2021-02-11 16:23 UTC, RobinKavPA requested changes

2021-02-11 16:23 UTC, RobinKavPA commented on src/pages/DataAccessRequest/DataAccessRequest.js
> +						{
If you wrap the anchor tag and only show it if the user is the applicant.

There is a property called user type you can use.

this.state.userType === 'APPLICANT'

2021-02-11 16:23 UTC, RobinKavPA commented on src/pages/DataAccessRequest/DataAccessRequest.js
> +						{
{
	userType.toUpperCase() === 'APPLICANT' && (
		<a
			className={`linkButton white-14-semibold ml-2 ${
				allowedNavigation && !this.state.readOnly ? '' : 'disabled'
			}`}
			onClick={this.onClickMailDAR}
			href=''
		>
			Mail DAR
		</a>
	);
}

2021-02-17 16:27 UTC, CMarksPA approved these changes

2021-02-17 16:27 UTC, PaulMcCaffertyPA approved these changes

2021-02-17 16:39 UTC, CMarksPA approved these changes

2021-02-17 16:54 UTC, RobinKavPA approved these changes

2021-02-17 16:54 UTC, merged