Feature/activity log card
HDRUK/gateway-web pull request #908
Opened 2021-11-08 13:59 UTC by kandaj

2021-11-08 14:34 UTC, sikenyonhdruk requested changes

2021-11-08 14:34 UTC, sikenyonhdruk commented on src/pages/dashboard/Components/ActitvityLogCard/ActivityLogCard.test.jsx
> +				event.detailedText && expect(screen.getByTestId(`event-detailed-text-${i}`)).toHaveClass('jumbotron');
I think this should be split out into a seperate test that only asserts whether it is visible/not visible

2021-11-08 14:34 UTC, sikenyonhdruk commented on src/pages/dashboard/Components/ActitvityLogCard/mockData.js
> +// };
This can be deleted

2021-11-08 14:34 UTC, sikenyonhdruk commented on src/pages/dashboard/Components/ActitvityLogCard/ActivityLogCard.test.jsx
> +				// expect(screen.getByTestId(`event-detailed-text-${i}`)).toHaveTextContent(event.detailedText);
Commented out code can be deleted

2021-11-08 14:34 UTC, sikenyonhdruk commented on src/utils/GeneralHelper.util.js
> +		timeOnly: moment(timestamp).format('HH:mm'),
It's generally preferred to use date-fns over moment. Moment is bloated and slows page rendering down as a new moment object is created everytime it's used. Date-fns is already in the dependencies so I would use that instead.

See https://javascript-conference.com/blog/why-you-should-use-date-fns-for-manipulating-dates-with-javascript/

2021-11-08 17:07 UTC, ThinkingMonkeyLtd reviewed
Create a index.js

2021-11-08 21:57 UTC, kandaj commented on src/utils/GeneralHelper.util.js
>  import _ from 'lodash';
done

2021-11-09 09:59 UTC, ThinkingMonkeyLtd commented on src/pages/dashboard/Components/ActitvityLogCard/ActivityLogCard.jsx
> +ActivityLogCard.propTypes = {
Can we add a common proptype shape for activity log response from the API response which we can use elsewhere?

**[...wherever components is]/ActivityLog.js**

```
export const ACTIVITY_LOG_PROP_TYPES = ACTIVITY_LOG_POST_RESPONSE;

ActivityLogCard.propTypes = ACTIVITY_LOG_PROP_TYPES;
```

**service/activitylog/activitylog.propTypes.js:**

```
export const ACTIVITY_LOG_POST_RESPONSE = PropTypes.shape({
   ...shape goes here
})
```

2021-11-12 09:38 UTC, ThinkingMonkeyLtd approved these changes

2021-11-12 12:13 UTC, ThinkingMonkeyLtd approved these changes

2021-11-12 12:16 UTC, merged